### ISSUE TITLE
how to add image to worksheet?

### ISSUE THREAD

**Issue by joonhwan** [dbzhang800/QtXlsxWriter#1]
Hi, thanks for sharing this nice code(even beautiful looking)

After fork, I'm trying to figure out how to add image to worksheet. 
Your code taugh me much about the xls code.(spec document is hard to understand for me). 

After I uncompress xlsx file int raw dir/files, I found that there is

xl/media

folder  containing the image files that I inserted into worksheet, but cannot figure out how to reference them in xml file. Any hint or support for this function?

**Comment by MartinChan3** [comment]
I want to ask how to get an image from a .xlsx file when u using QtXlsx?It seems it only supplies the insertImage() function...
