### ISSUE TITLE
Can't find the content of CellRange Class in documentation

### ISSUE THREAD

**Issue by MartinChan3** [dbzhang800/QtXlsxWriter#120]
[Documentation](http://qtxlsx.debao.me/qtxlsx-module.html) is here and I can't find any information about the CellRange Class...

**Comment by VSRonin** [comment]
It's more or less a rectangle of Cell, the [source](https://github.com/dbzhang800/QtXlsxWriter/blob/master/src/xlsx/xlsxcellrange.h) is quite self explanatory. Do you have any doubt in particular?

**Comment by MartinChan3** [comment]
@VSRonin Thx,
