### ISSUE TITLE
Extracting data from a password protected xlsx file?

### ISSUE THREAD

**Issue by dillydill123** [dbzhang800/QtXlsxWriter#121]
Hello, I'm using QtXlsxWriter with Qt 5.6 (using the updated one by VSRonin), and I have been able to read and write to xlsx files just fine. However, I am trying to read from a password protected xlsx file (just read, not write) and I am not able to do so. I have no compiling errors, but the Application output on Qt says the following:

`QZip: not a zip file!`

I am only running one line of code:

`QXlsx::Document excel("path\\to\\xlsx");`

Is it possible to read from a password protected xlsx file? Thanks for any guidance

**Comment by VSRonin** [comment]
This feature is currently not supported.
The error you are getting is due to the structure of a protected workbook being completely different from a normal one.
If you open a protected and unprotected file with a zip reader (e.g. [7zip](http://www.7-zip.org/) ) you'll clearly see what I mean

**Comment by dillydill123** [comment]
Thank you for a quick response.

**Comment by VSRonin** [comment]
if you or anybody else is interested in adding this feature the reference is section 17.15.1.29 of the current (2012) standard
