### ISSUE TITLE
large string was cutted in xlsx file

### ISSUE THREAD

**Issue by vt-schmit** [dbzhang800/QtXlsxWriter#127]
Hy,

I tried to write an string with 32760 characters into an xlsx cell. The string was not fully writen into the xlsx file. Why not is there a limit?

I used the method xlsx.write()

**Comment by vt-schmit** [comment]
i found something in the code:
const int XLSX_ROW_MAX = 1048576;
const int XLSX_COLUMN_MAX = 16384;
const int XLSX_STRING_MAX = 32767;

Why are there limits?

**Comment by VSRonin** [comment]
It's not a limit of this library but of excel: https://support.office.com/en-us/article/excel-specifications-and-limits-16c69c74-3d6a-4aaf-ba35-e6eb276e8eaa

**Comment by vt-schmit** [comment]
ahhh ok thx
