### ISSUE TITLE
xlsx file finds error and attempts to repair after being written to.

### ISSUE THREAD

**Issue by dillydill123** [dbzhang800/QtXlsxWriter#128]
With Qt 5.6, I attempt to write to an existing xlsx document, but when I open that xlsx document after it has been opened, I get the following message from microsoft:

> We found a problem with some content in [xlsx file]. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes.

After I click yes, the xlsx loads up and the data written is in the corresponding cell, but I get a dialogue showing the attempted repairs to the excel file.

I have tried inserting QStrings, ints, doubles and QVariants as the third parameter for the write method, and I still receive this behavior.

This does not occur when I create a new xlsx and write to it.

Here is the code inserting the data:

`QXlsx::Document xlsx(path/to/xlsx);`
`xlsx.selectSheet(sheetName);`
`xlsx.write(29, 4, QVariant(24));`
`xlsx.save();`

What could be causing this error message to show up? How can I prevent it?

EDIT:
I have also noticed that I am losing data on some of the excel files after I am done writing to them. I'm losing formatting and images most of the time. Why is this occuring?

Edit 2:
It appears that the drawing.xml files are getting corrupted when I write to the excel file. Before the write, I saved the drawing.xml files. Then I performed the write method and attempted to open the updated excel file, only to get the same error. However, I unzipped the xlsx and replaced the drawing.xml files with the old ones, and it worked! The new data was written to the file and xlsx didnt lose anything else. Why are the drawing.xml files being corrupted?

**Comment by VSRonin** [comment]
This library does not support images yet so when it saves drawing.xml it omits parts that are referenced in other files of the archive and that's what triggers the "recovery attempt"
If you do not perform any action involving drawings (charts) you colud just use a zip libaray (KArchive or Quazip) to unpack the drawing.xml before opening the file, do the edit with this library, save and then put back the old drawings.xml to the new archive

**Comment by dillydill123** [comment]
Thank you for the response. I will proceed with the method you have mentioned. Here is my line of thinking for editing the xlsx file.

1. Unpack the original xlsx
2. Save the drawing.xml files
3. Write to xlsx
4. Unpack updated xlsx
5. Replace drawing.xml in updated xlsx with old ones
6. pack back into xlsx

I have not used Quazip or KArchive before (I was just planning on using 7zip), will they facilitate this process? Lastly, are there any other xml files that may be corrupted that I would have to replace?

Thank you.

**Comment by RedaMazoz** [comment]
Hi, Thank you for this temporary solution @VSRonin 
however, I'm surprised I didn't have this issue before with the same type of files etc..
I was able to modify files etc.. directly


but wait ..
Actually I discovered that this issue happens with some xlsx files while some other ones, not
I have no idea how I can help beside sharing with you 2 xlsx files, one which works correctly and get written to correctly, one which triggers the repair file error and even when you repair, the sheet doesn't get written 2 and becomes empty even if you click repair and the file sheet is not empty

ps: I'm using QXlsx not QtXlsxWriter, but I believe its build on top of QtXlsxWriter

**Comment by RedaMazoz** [comment]
Ok, so @VSRonin you were right

your thought about drawing.xml made me realize that I had unintentionally put a hypertext in a cell, which triggered the problem on my side

once I removed that hyperlink, there were no problems anymore

Thx Again !
