### ISSUE TITLE
Could it Edit an existing .xlsx file?

### ISSUE THREAD

**Issue by xbotao** [dbzhang800/QtXlsxWriter#152]
there is not a link for ` Edit an existing .xlsx file ` in your [pages](http://qtxlsx.debao.me/).
Could it do this?

**Comment by VSRonin** [comment]
Yes and no. 
Yes it can open existing files, change them and save them (basically combine the read and write examples) but any unsupported feature will not be saved. For example, data tables will be lost

**Comment by xbotao** [comment]
Thanks

**Comment by userjia** [comment]
Is there some way to solve this?
