### ISSUE TITLE
Read the value, not the formula computing it from excel document

### ISSUE THREAD

**Issue by Darker** [dbzhang800/QtXlsxWriter#156]
I have a document that generates some field's values using formulas. I am only reading those values, the document is created using excel.

The problem is, that the `document->read(x, y)` returns the formula as tring instead of the field value. Is there any workaround for this?

**Comment by majidkamali1370** [comment]
Use `Cell::value()`

```c++
Cell *cell = document->cellAt(x, y);
QVariant val = cell->value();
```

**Comment by Darker** [comment]
Thanks, it works.
