### ISSUE TITLE
Reading .xls

### ISSUE THREAD

**Issue by supertriodo** [dbzhang800/QtXlsxWriter#157]
Hi I'm looging for a library to read a .xls file.

Does Qt Xlsx do the job?

Attached a .xls file example of what I want to read.
[arenamastery_export.xls.zip](https://github.com/dbzhang800/QtXlsxWriter/files/1013962/arenamastery_export.xls.zip)

Cheers

**Comment by VSRonin** [comment]
This library does not and never will deal with old format excel files (xls).
If you only need to read xls files you can use ODBC sql driver: http://wiki.qt.io/Handling_Microsoft_Excel_file_format#Using_ODBC

**Comment by supertriodo** [comment]
ok, thanks!
