### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by HaodaGitHub** [dbzhang800/QtXlsxWriter#165]
this error:
QtXlsxWriter\trunk\src\xlsx\xlsxzipreader.cpp:51: error: invalid use of incomplete type 'class QVector<QZipReader::FileInfo>'
     QList<QZipReader::FileInfo> allFiles = m_reader->fileInfoList();
                                                                   ^

**Comment by VSRonin** [comment]
Duplicate of #125

**Comment by HaodaGitHub** [comment]
Has been resolved

add the head #include <QVector> in xlsxzipreader.cpp AND QList -> QVector   

rebuild   

must qmake    make
