### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by heyuanjie87** [dbzhang800/QtXlsxWriter#176]
\xlsx\xlsxzipreader.cpp:51: error: conversion from 'QVector<QZipReader::FileInfo>' to non-scalar type 'QList<QZipReader::FileInfo>' requested
     QList<QZipReader::FileInfo> allFiles = m_reader->fileInfoList();
                                                                  ^

**Comment by VSRonin** [comment]
Use this fork: https://github.com/VSRonin/QtXlsxWriter
