### ISSUE TITLE
Casting problem

### ISSUE THREAD

**Issue by thomas-leanfa** [dbzhang800/QtXlsxWriter#177]
https://github.com/dbzhang800/QtXlsxWriter/blob/ad90b6a2c21b300138ceb9fe9030a5917230f92d/src/xlsx/xlsxzipreader.cpp#L51

Line 51:
**QList**`<QZipReader::FileInfo> allFiles = m_reader->fileInfoList();` 
must to be changed to: 
**QVector**`<QZipReader::FileInfo> allFiles = m_reader->fileInfoList();`

**Comment by VSRonin** [comment]
Duplicate of #125
