### ISSUE TITLE
Crash when using sheetmodel in qtableview

### ISSUE THREAD

**Issue by bascyr** [dbzhang800/QtXlsxWriter#181]
Hi,

I try to extract xlsx sheets (microsoft) in a differents QTableView.
One sheet (xlsx microsoft excel) for one QTableView which is in one tab of a QTabWidget.
QTabWidget was placed with QTDesigner.

I strangely discover that windows crashes when I run this following code

            `QXlsx::Document xlsx(filename.toUtf8());
              foreach (QString sheetName, xlsx.sheetNames()) {
                  Worksheet *sheet = dynamic_cast<Worksheet *>(xlsx.sheet(sheetName));
                  if (sheet) {
                      QTableView *view = new QTableView(ui->tabWidget);
                      view->setModel(new SheetModel(sheet, view));
                      ui->tabWidget->addTab(view, sheetName);
                  }
             }`            
Any ideas welcome to help understanding why it crashed.
Thanks for answers.

**Comment by VSRonin** [comment]
+ Can you post the stack trace?
+ Are you sure `xlsx` does not go out of scope?

**Comment by VSRonin** [comment]
Yes, you need to keep `Document xlsx2(filePath);` alive. Make it a member of MainWindow instead of a local variable

**Comment by VSRonin** [comment]
> Even if I don't oversee why windows crashed...

`SheetModel` doesn't copy or takes ownership of the `QXlsx::Document`. If you delete it, the model will try to access a dangling pointer

In any case, your code above is leaking `xlsx2`, you should pass a parent (`this`?) to the constructor.

If your problem is solved please close the ticket

**Comment by bascyr** [comment]
Thanks for answers.
