### ISSUE TITLE
"Save" to clipboard

### ISSUE THREAD

**Issue by sergio-vedois** [dbzhang800/QtXlsxWriter#185]
Hi,
I have a QTableWidget filled with data wich I would like to copy and then paste into Excel sheet.
I already able to copy/paste as csv file, but I want add attributes.
If it is possible, could you send an example ?

**Comment by VSRonin** [comment]
This has nothing to do with this library.
You could copy data from excel then inspect the available mime types in the clipboard, detect the one that supports all the "attributes" you require, look up its specification and implement it in your application
