### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yangyid** [dbzhang800/QtXlsxWriter#193]
F:\test\qtxlxs\QtXlsxWriter-master\QtXlsxWriter-master\src\xlsx\xlsxzipreader.cpp: In member function 'void QXlsx::ZipReader::init()':
F:\test\qtxlxs\QtXlsxWriter-master\QtXlsxWriter-master\src\xlsx\xlsxzipreader.cpp:51:66: error: conversion from 'QVector<QZipReader::FileInfo>' to non-scalar type 'QList<QZipReader::FileInfo>' requested
     QList<QZipReader::FileInfo> allFiles = m_reader->fileInfoList();
                                            ~~~~~~~~~~~~~~~~~~~~~~^~
mingw32-make[3]: *** [Makefile.Release:2032: .obj/release/xlsxzipreader.o] Error 1

**Comment by VSRonin** [comment]
Duplicate of #125

**Comment by dbzhang800** [comment]
Fixed
