### ISSUE TITLE
Could you please make a LICENSE file for this project?

### ISSUE THREAD

**Issue by Antonio0317** [dbzhang800/QtXlsxWriter#194]
I want to use this for my new project so I need a LICENSE file.
Could you make it?

**Comment by Antonio0317** [comment]
I found some information and it's MIT license, isn't it??
Like other projects which use MIT license, plz make a LICENSE file!
It will be really thankful to me and also others.

**Comment by dbzhang800** [comment]
OK, LICENSE file has been added.
