### ISSUE TITLE
Ask for a new release (0.3.1) with the LICENSE file

### ISSUE THREAD

**Issue by jgsogo** [dbzhang800/QtXlsxWriter#210]
Hi! 

Is it possible to get a new release/tag including the LICENSE file? It will help us to package your library in [ConanCenter](https://conan.io/center) and make it easily accessible for other developers.

Thanks!

**Comment by VSRonin** [comment]
This repository hasn't been maintained in forever, if you want to add a Qt excel library to Conan it should be https://github.com/QtExcel/QXlsx that sprung from this repository but then took a different route and is actively maintained

**Comment by vaerizk** [comment]
@VSRonin Thanks for your suggestion but we have a project that uses [QtXlsxWriter](https://github.com/dbzhang800/QtXlsxWriter) and since we are actively working with the Conan package manager, it would be nice to have this library in [ConanCenter](https://conan.io/center).

**Comment by VSRonin** [comment]
I wouldn't hold my breath on this one. The author has not been online much. I see you already have a workaround in place I would suggest you use it

**Comment by jgsogo** [comment]
It's been added to ConanCenter 🚀 : https://conan.io/center/qtxlsxwriter
