### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by jayasi** [dbzhang800/QtXlsxWriter#39]
Opening the project in QT creator gives the following errors: 

Project ERROR: Unknown module(s) in QT: xlsx
Project WARNING: You should probably load(qt_build_config) first in xlsx.pro for QtXlsx, as the latter also load()s qt_module.
Project MESSAGE: Not doing so may lead to qt_module.prf overriding compiler/linker options in your .pro file.
Project MESSAGE: Ignore this warning with CONFIG+=no_qt_module_warning if you know what you are doing.
Project ERROR: Module does not define version.
Project ERROR: Unknown module(s) in QT: xlsx
Project ERROR: Unknown module(s) in QT: xlsx
Project ERROR: Unknown module(s) in QT: xlsx
Project ERROR: Unknown module(s) in QT: xlsx-private xlsx
Project ERROR: Unknown module(s) in QT: xlsx-private xlsx
Project ERROR: Unknown module(s) in QT: xlsx-private xlsx
Project ERROR: Unknown module(s) in QT: xlsx-private xlsx
Project ERROR: Unknown module(s) in QT: xlsx-private xlsx
Project ERROR: Unknown module(s) in QT: xlsx-private xlsx
Project ERROR: Unknown module(s) in QT: xlsx-private xlsx
Project ERROR: Unknown module(s) in QT: xlsx-private xlsx
Project ERROR: Unknown module(s) in QT: xlsx-private xlsx
Project ERROR: Unknown module(s) in QT: xlsx-private xlsx
Project ERROR: Unknown module(s) in QT: xlsx
Project ERROR: Unknown module(s) in QT: xlsx
Project ERROR: Unknown module(s) in QT: xlsx
Project ERROR: Unknown module(s) in QT: xlsx

If I try building it, I get the following error - 

Executable F:\QtXlsxWriter\build-qtxlsx-Desktop_Qt_5_3_0_MSVC2012_OpenGL_32bit-Debug\tests\auto\format\debug\tst_format.exe does not exist.

**Comment by Larz60p** [comment]
during make install, I noticed many: 'make[2]: [install_private_headers] Error 1 (ignored)' errors
for example: strip: .../Qt/5.4/gcc_64/include/QtXlsx/0.3.0/QtXlsx/private/xlsxcontenttypes_p.h: File format not recognized
When I try to use the package from within Qt5 creator, I get the same error as dbzhang800
Cannot open include file: 'xlsxdocument.h': No such file or directory
However if I use a shell script that I made:
<code>
qmake -project
pname=${PWD##*/}
FILE=$pname'.pro'
FILE_O=$FILE'1'
echo $FILE

if [ ! -f "$file" ] ; then
    # if not create the file
    touch "$FILE_O"
else
    rm "$FILE_O"
    touch "$FILE_O"
fi

while read line; do
    echo $line >> $FILE_O
    if [ "$line" == "INCLUDEPATH += ." ]; then
        echo "QT += core widgets gui" >> $FILE_O
        echo "QT += xlsx" >> $FILE_O
    fi
done < $FILE
rm "$FILE"
mv "$FILE_O" "$FILE"
qmake "$FILE"
make
</code>
I can compile without errors,
I am using Linux, Mint17 with Qt5
