### ISSUE TITLE
Setting the background colour to any colour creates black cells.

### ISSUE THREAD

**Issue by Alzathar** [dbzhang800/QtXlsxWriter#4]
I use the method `QXlsx::Format::setPatternBackgroundColor` to set the background colour but the result is always a cell with a black colour. Looking in Excel (2011 - MacOS 10.8.4), it sets the value to the foreground colour (while in the file, the element used is correctly "bgColor"...). Doing the opposite (i.e. using the method `QXlsx::Format::setPatternForegroundColor`) resolves my problem. Excel correctly paints the cell's background (cell property show that colour is set for the background colour and in the file the element used is "fgColor" ...).

I don't know if it is an issue related to Excel 2011 or if the setting of both, the foreground and the background colours, are required to display correctly the background colours. I will try to investigate this problem under Windows.

**Comment by patchcad** [comment]
I'm still experiencing this background colour turning black issue with the latest version. Has this really been resolved?
