### ISSUE TITLE
soname prefix is libQt0

### ISSUE THREAD

**Issue by nblock** [dbzhang800/QtXlsxWriter#79]
I just noticed, that QtXlsx has a default soname prefix of libQt0. This is due to `MODULE_VERSION = 0.3.0` in .qmake.conf. Since this is a Qt5 library, wouldn't something like `MODULE_VERSION = 5.x.y` fit better?

**Comment by dbzhang800** [comment]
Hi, thanks for your feedback. This bug has been fixed in Qt5.4, more information can be found in https://bugreports.qt.io/browse/QTBUG-30910

**Comment by nblock** [comment]
Ah, thx for the hint, I wasn't aware of this.
