### ISSUE TITLE
DataValidation Type List

### ISSUE THREAD

**Issue by slevon** [dbzhang800/QtXlsxWriter#86]
Hello, 
First of all thank you for your great lib!
I have a Problem with DataValidation __Type List__. I tried several approaches to achieve the validation.

As from your example I tried;:
 ```c++
 //! 1
DataValidation validation(DataValidation::List, DataValidation::Equal, "ON\nOFF");
 //! 2 
DataValidation validation(DataValidation::List, DataValidation::Equal, "ON;OFF");
 //! 3
DataValidation validation(DataValidation::List, DataValidation::Equal, "\"ON\";\"OFF\"");
 //! 4 
DataValidation validation(DataValidation::List, DataValidation::Equal, "ON,OFF");
 //! 5 
DataValidation validation(DataValidation::List, DataValidation::Equal, "ON\tOFF");
 //! 6
DataValidation validation(DataValidation::List, DataValidation::Equal, "ON","OFF");
```
and a lot of other things. 
All this did not result in a Dropdownlist. There where serveral errors (Err:509,Err510,Err520) which are all related to fromulars.
If you could give me a hint on how to achive this I would create a imporved datavalidation example and update the documentation and send it as pull request If you like. 

Best regards,
slevon

**Comment by zhangshaowei** [comment]
I do it like this, it works.
DataValidation validation(DataValidation::List, DataValidation::Equal, "\"ON,OFF\"");

**Comment by slevon** [comment]
Hi, 
thank you!

I'll give it a try and Report back.

Cheers,
slevon

**Comment by slevon** [comment]
Hello,
it works great. Thank you!
